@startuml DevStack

!include <logos/docker>
!include <logos/github>
!include <osa/laptop/laptop>
!include <tupadr3/common>
!include <tupadr3/font-awesome/server>
!include <tupadr3/devicons/postgresql>
!include <kubernetes/k8s-sprites-unlabeled-25pct>


FA_SERVER(server, SERVEUR)
' DEV_POSTGRESQL(db4,Postgresql,database)

' rectangle "<$docker> service" as docker
rectangle "<$master>\ngithub actions" as github
rectangle "<$laptop>\nDeveloppeur" as dev


dev --> github : Git push
github --> server : Git pull


@enduml