@startuml DevStack

package Docker{
    rectangle Traefik[
        Reverse proxy
        <img:img/traefik.jpeg>
    ]
}

package Docker.Monitoring{
    
    rectangle Prometheus[
        <img:img/prometheus.png>
    ]

    rectangle Grafana[
        <img:img/grafana.png>
    ]
}

package Docker.Suptrack{
    rectangle App [
        Web App
        <img:img/django.png>
    ]

    database Mysql[
        DB
        <img:img/mysql.jpeg>
    ]

    database Redis[
        Cache
        <img:img/redis.png>
    ]

    Grafana <--> Traefik: grafana.monotoring.com:80
    Prometheus <--> Traefik: prometheus.monotoring.com:80
    App <--> Traefik : app.com:80
    Mysql <--> App
    App <--> Redis

}

@enduml