services:
  redis:
    image: redis:latest
    container_name: redis-container
    expose:
      - 6379
    volumes:
      - ./data:/data
    networks:
      - redis_network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  redis_network:
    name: redis_network
    external: true
